import { Montserrat } from 'next/font/google';



const montserrat = Montserrat({
  weight: ['100','200','300', '400', '500','600', '700','800','900'],
  subsets: ['latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
});


export const metadata = {
  title: 'Smartwebin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
